### PR TITLE
Fix ConcurrentModificationException in `DefaultDiffProcessor#updateProgressMap`

### LINKED ISSUE #165: Concurrent exception when values emitting is too fast
Hi, i have the issue when the async incoming data arrive to fast (during 1 ms).
` FATAL EXCEPTION: pool-10-thread-1
                                                                                                    Process: 
                                                                                                    java.util.ConcurrentModificationException
                                                                                                    	at java.util.ArrayList$Itr.next(ArrayList.java:860)
                                                                                                    	at com.patrykandpatryk.vico.core.entry.diff.DefaultDiffProcessor.updateProgressMap(DefaultDiffProcessor.kt:220)
                                                                                                    	at com.patrykandpatryk.vico.core.entry.diff.DefaultDiffProcessor.setEntries(DefaultDiffProcessor.kt:50)
                                                                                                    	at com.patrykandpatryk.vico.core.entry.ChartEntryModelProducer.setEntries$lambda$1$lambda$0(ChartEntryModelProducer.kt:73)
                                                                                                    	at com.patrykandpatryk.vico.core.entry.ChartEntryModelProducer.$r8$lambda$ouCUkSdPZbczQqr-7snrCS2u75g(Unknown Source:0)
                                                                                                    	at com.patrykandpatryk.vico.core.entry.ChartEntryModelProducer$$ExternalSyntheticLambda0.run(Unknown Source:4)`

I have 300-500 dots of line chart on a screen, and i update the chart entry on every new dot. And the way of such chart update seems to be not thread-safe.
Is there any way of synchronization inside of ChartEntryModelProducer?

### PR DESCRIPTION
**Pull request by Gowsky**
This fixes #165.

### CODE REVIEW

File: vico/core/src/main/java/com/patrykandpatryk/vico/core/extension/CollectionExtensions.kt [hunk 1]
```diff
@@ -32,6 +32,26 @@ public fun <T> MutableList<T>.setAll(other: Collection<T>) {
     addAll(other)
 }
 
+/**
+ * Replaces all of the elements in child [ArrayList]s of this [ArrayList] with the elements of the provided [List].
```
Comment (patrickmichalik) [inline vico/core/src/main/java/com/patrykandpatryk/vico/core/extension/CollectionExtensions.kt:36]: I’d suggest making the documentation for `setToAllChildren` a bit more precise.

```suggestion
 * For each child [ArrayList] contained in this [ArrayList], replaces the elements of the child [ArrayList] with the
 * elements of the corresponding [Collection] from the provided [List]. The child [ArrayList] and [Collection] are
 * associated by index. If a given child [ArrayList] contained in this [ArrayList] has no corresponding [Collection] in
 * the provided [List], the child [ArrayList] will be cleared. If the size of this [ArrayList] is smaller than the size
 * of the provided [List], an appropriate number of empty child [ArrayList]s will first be added to this [ArrayList].
```

**Review by patrickmichalik — CHANGES_REQUESTED** [review]

**Review by patrickmichalik — APPROVED** [review]
