### PR TITLE
Fix `CartesianChartView` mishandling padding

### LINKED ISSUE #1202: It will crash when the chart scroll after chart marker show
### Example

I have an example of what I have in my app here:  https://github.com/Haha003/app_vico_test/tree/main/app-vico-test/src/main/java/com/dsul/app_vico_test

### How to reproduce

scroll the chart, it will crash

### Observed behavior

application crashed ,and the log is 

Image

### Expected behavior

application not crash

### Module(s)

views

### Platform(s)

Android

### Platform version(s)

android 12

### Vico version(s)

2.3.6

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by patrickmichalik**
This resolves #1202.

### CODE REVIEW

File: vico/views/src/main/java/com/patrykandpatrick/vico/views/common/ChartView.kt [hunk 1]
```diff
@@ -199,6 +210,21 @@ constructor(context: Context, attrs: AttributeSet? = null, defStyleAttr: Int = 0
     @Suppress("UNNECESSARY_SAFE_CALL")
     measuringContext?.isLtr = layoutDirection == LAYOUT_DIRECTION_LTR
   }
+
+  protected fun MotionEvent.translateOrReject(): Boolean {
+    val action = action and MotionEvent.ACTION_MASK
```
Comment (Gowsky) [inline vico/views/src/main/java/com/patrykandpatrick/vico/views/common/ChartView.kt]: You can use `actionMasked` here instead.

File: vico/views/src/main/java/com/patrykandpatrick/vico/views/common/ChartView.kt [hunk 2]
```diff
@@ -199,6 +210,21 @@ constructor(context: Context, attrs: AttributeSet? = null, defStyleAttr: Int = 0
...
+    if (action == MotionEvent.ACTION_DOWN) {
+      acceptMotionEvents =
+        (0..pointerCount - 1).all { index ->
```
Comment (Gowsky) [inline vico/views/src/main/java/com/patrykandpatrick/vico/views/common/ChartView.kt]: What about using `until` instead here?
```suggestion
        (0 until pointerCount).all { index ->
```

File: vico/views/src/main/java/com/patrykandpatrick/vico/views/common/ChartView.kt (hunk 1 above)
Comment (patrickmichalik) [reply vico/views/src/main/java/com/patrykandpatrick/vico/views/common/ChartView.kt]: Addressed in [`f6ab1c3`](https://github.com/patrykandpatrick/vico/pull/1223/commits/f6ab1c329b5ef2f9a17525a44d2329f4404a2997).

File: vico/views/src/main/java/com/patrykandpatrick/vico/views/common/ChartView.kt (hunk 2 above)
Comment (patrickmichalik) [reply vico/views/src/main/java/com/patrykandpatrick/vico/views/common/ChartView.kt]: Better yet, we can use `..<`. I’ve switched to it in [`f6ab1c3`](https://github.com/patrykandpatrick/vico/pull/1223/commits/f6ab1c329b5ef2f9a17525a44d2329f4404a2997).

File: vico/views/src/main/java/com/patrykandpatrick/vico/views/common/ChartView.kt [hunk 3]
```diff
@@ -199,6 +210,20 @@ constructor(context: Context, attrs: AttributeSet? = null, defStyleAttr: Int = 0
...
+  protected fun MotionEvent.translateOrReject(): Boolean {
+    if (actionMasked == MotionEvent.ACTION_DOWN) {
+      acceptMotionEvents =
+        (0..<pointerCount).all { index ->
+          getX(index) in offset.x..offset.x + canvasSize.width &&
+            getY(index) in offset.y..offset.y + canvasSize.height
+        }
+    }
+    if (!acceptMotionEvents) return false
+    if (actionMasked == MotionEvent.ACTION_UP) acceptMotionEvents = false
```
[the remark this answers is not in the document]
Comment (patrickmichalik) [reply vico/views/src/main/java/com/patrykandpatrick/vico/views/common/ChartView.kt]: Addressed in [`6e9cbcf`](https://github.com/patrykandpatrick/vico/pull/1223/commits/6e9cbcf77bc6f2e2ed2fa917f43eaf180a3018b8).

**Review by Gowsky — APPROVED** [review]
