### PR TITLE
Crash #115 marker

### LINKED ISSUE #115: Crash on specific range for random entries generation while drawing a label
Hard to reproduce.
For example, we have a following random entries generation config:
```
private val generator = RandomEntriesGenerator(
        xRange = IntProgression.fromClosedRange(0, 24, 2),
        yRange = 0..1000,
    )
```
The chart has a label, the code is almost the same which is given in the sample, only UI settings are different.
For this chart:
Снимок экрана 2022-08-07 в 17 00 02
When we tap on the lowest point to see the label, a crash is happening:
```
java.lang.IllegalArgumentException: Cannot coerce value to an empty range: maximum 513.1875 is less than minimum 530.1875.
        at kotlin.ranges.RangesKt___RangesKt.coerceIn(_Ranges.kt:1263)
        at com.patrykandpatryk.vico.core.component.shape.cornered.MarkerCorneredShape.drawShape(MarkerCorneredShape.kt:86)
        at com.patrykandpatryk.vico.core.component.shape.ShapeComponent.draw$lambda-3$drawShape(ShapeComponent.kt:99)
        at com.patrykandpatryk.vico.core.component.shape.ShapeComponent.draw(ShapeComponent.kt:110)
        at com.patrykandpatryk.vico.core.component.text.TextComponent.drawText(TextComponent.kt:200)
        at com.patrykandpatryk.vico.core.component.text.TextComponent.drawText$default(TextComponent.kt:133)
        at com.patrykandpatryk.vico.core.component.marker.MarkerComponent.drawLabel(MarkerComponent.kt:104)
        at com.patrykandpatryk.vico.core.component.marker.MarkerComponent.draw(MarkerComponent.kt:89)
```
I've checked multiple times, the lowest point has to be close to zero:
Снимок экрана 2022-08-07 в 17 05 00
`java.lang.IllegalArgumentException: Cannot coerce value to an empty range: maximum 80.1875 is less than minimum 97.1875.`

Another sample:
Снимок экрана 2022-08-07 в 17 07 20
Снимок экрана 2022-08-07 в 17 07 23
Crash on tap on the lowest point:
`    java.lang.IllegalArgumentException: Cannot coerce value to an empty range: maximum 645.1875 is less than minimum 662.1875.
`

No crash when I update the generation this way:
```
private val generator = RandomEntriesGenerator(
        xRange = IntProgression.fromClosedRange(0, 24, 2),
        yRange = 100..1000,
    )
```

### PR DESCRIPTION
**Pull request by Gowsky**
This PR fixes #115, incorrect calculation of corner scale for sharp corners, and marker indication in `ColumnChart` going out of bounds.

### CODE REVIEW

File: vico/core/src/main/java/com/patrykandpatryk/vico/core/component/shape/cornered/MarkerCorneredShape.kt [hunk 1]
```diff
@@ -81,12 +82,19 @@ public open class MarkerCorneredShape(
             val cornerScale = getCornerScale(right - left, bottom - top, density)
 
             val minLeft = left + bottomLeft.getCornerSize(availableCornerSize, density) * cornerScale
-            val maxLeft = right - (bottomRight.getCornerSize(availableCornerSize, density) * cornerScale + tickSize * 2)
+            val maxLeft = right - (bottomRight.getCornerSize(availableCornerSize, density) * cornerScale)
```
Comment (patrykmichalik) [inline vico/core/src/main/java/com/patrykandpatryk/vico/core/component/shape/cornered/MarkerCorneredShape.kt:85]:
```suggestion
            val maxLeft = right - bottomRight.getCornerSize(availableCornerSize, density) * cornerScale
```

**Review by patrykmichalik — CHANGES_REQUESTED** [review]

**Review by patrykmichalik — APPROVED** [review]
